name: Deploy subgraph

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: ["production", "staging"]

    env:
      TYPE: ${{ matrix.type }}
      SUBGRAPH_NAME: khelil/starknet-bridge-${{ matrix.type }}
      THEGRAPH_ACCESS_TOKEN: ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Build and deploy ${{ matrix.type }}
        run: yarn deploy
